version: '3.8'
services:
    tomcat:
        image: tomcat:9.0
        ports:
            - "8080:8080"
        volumes:
            - ./servlet-advice/target/servlet-advice.war:/usr/local/tomcat/webapps/ROOT.war
            - ./conf/Catalina/localhost:/usr/local/tomcat/conf/Catalina/localhost
        restart: on-failure